# TRS-ALLIANCE OFFICIAL BUILD CONFIG
# EMPEROR-CERTIFIED 2025

[build]
  command = "bash scripts/build.sh"
  publish = "out"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  TRS_ENV = "production"
  NEXT_PUBLIC_FIREBASE_API_KEY = "YOUR_PUBLIC_KEY" # Safe
  NEXT_PUBLIC_PROJECT_ID = "YOUR_FIREBASE_PROJECT_ID"
  POETIC_FOG_SEED = "lion_gate_whispers_11" # Public-facing

[context.production]
  environment = { 
    TRS_DEPLOY = "VALIDATED", 
    SENTINEL_LOG_LEVEL = "3" 
  }
