name: TRS Deploy & Validate

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install deps
        run: pnpm install

  lint-and-build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build

  deploy:
    needs: lint-and-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/YOUR_HOOK_ID
